name: "Publish markdown to Discord"
description: "Send markdown file to Discord as message using webhook"

inputs:
  file:
    description: "Which file to send"
    required: true
  webhook:
    description: "Discord webhook url to use"
    required: true
  outputFileLocation:
    description: "Where to write a file containing current message ids for this run"
    default: "./messageIDs.txt"
  storageMethod:
    description: |-
      Method of storing old message ids to delete
      one of:
      - none - doesn't store ids of sent messages
      - git - stores ids in git repository
    default: none
    required: true
  storegeGitFileLocation:
    description: "Where in git repository file should be saved"

runs:
  using: node20
  main: dist/index.js
